### ISSUE TITLE
Get max allowed pro users

### ISSUE THREAD

**Issue by delmicio** [zoom/api#10]
Hi,
When I try to create a new user with `cus-create-user` type pro I get a message that I reached the max allowed pro users in my account.

How do I get this information? so I can prevent creating pro users when there are no more licenses availables.

**Comment by joshuawoodward** [comment]
You can find this information on your Zoom account page http://zoom.us/billing under "My Subscriptions" in the "Count" column as "XXX hosts"

This is not available through an API call

**Comment by delmicio** [comment]
@joshuawoodward yes, I know how many licenses we have through the account page but how do I get that information with the API. 

I can get how many pro account are there already active but not how many licenses I have available to provide pro account.

I need to create the maximum allowed pro accounts through the API.

**Comment by joshuawoodward** [comment]
The don't believe that you can add licenses via the API, so it makes sense why there is not a get licenses API.

Seems like the best approach is a config/constant


```
//in config file
define("MAX_PRO_ACCOUNTS", 100);

//in logic
$number_of_current_pro = however_you_get_this();

if ($number_of_current_pro >= MAX_PRO_ACCOUNTS) {
 //do nothing, or log, or display error
} else {
 create_pro_account();
}
```
