### ISSUE TITLE
Optionals fields are not optional

### ISSUE THREAD

**Issue by davidgatti** [zoom/api#11]
I'm making a post request at `https://api.zoom.us/v2/users`, and passing the following object 

```javascript
{
	action: 'custCreate',
	user_info: {

	}
}
```
And I get back a response saying:

```Javascript
{
	code: 300,
	message: 'Validation Failed.',
	errors: [ 
		{ field: 'user_info.type', message: 'Missing field.' },
		{ field: 'user_info.email', message: 'Missing field.' } 
	]
}
```

Where if you go to the API documentation for [Create a user](https://zoom.github.io/api/#create-a-user) all the fields are optional.

I'm trying go create a Virtual User and I'm lost and frustrated.

**Comment by joshuawoodward** [comment]
@davidgatti 
Updated documentation. action, user_info.type and user_info.email are required, sorry for the confusion.

**Comment by davidgatti** [comment]
No worries, but your commit went to broad ;)
