### ISSUE TITLE
Push Notifications give certificate error

### ISSUE THREAD

**Issue by towhead09** [zoom/api#11]
Push notifications are not being sent from Zoom servers due to what appears to be a certificate configuration error

sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

looking at the discussion boards, this was an issue back in april...although we have only been experiencing it as of Aug 3/4..before that push notifications worked fine

**Comment by joshuawoodward** [comment]
Is the cert config error on your end? https://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find

**Comment by towhead09** [comment]
Thanks Josh, It does not appear to be, but I may be mistaken....The error message was retrieved from the 'Call Log' on the Zoom developer website. The certificate for our site is valid, and is not self-signed. All other clients connecting to our server do not receive this error. CURL works without producing this error. There are no access/error log entries of the push requests from Zoom reaching our server.  Also, referencing the stackoverflow link you included, this states that corrections need to be made on the 'client' machine....as these are 'push notifications' wouldn't Zoom be considered the client...and thus these changes be made on the Zoom end? Thanks for the help

**Comment by joshuawoodward** [comment]
@towhead09 can you email me you're account ID so I can look into the logs, joshua.woodward@zoom.us

**Comment by towhead09** [comment]
emailed...

**Comment by towhead09** [comment]
@joshuawoodward digging deeper into the issue, I found that there can be issues with JAVA and godaddy issued certificates. I've updated our certificate to include additional intermediary certificates issued from godaddy, and this seems to have fixed the issue...push notifications are reaching our server again.  thanks for your help

**Comment by joshuawoodward** [comment]
@towhead09 What was the issue exactly, another developer w/ JAVA and GoDaddy certs is experiencing the same

**Comment by towhead09** [comment]
Seems the java client installed on the Zoom server(s) is a bit fickle about the certificates, and needs the 'intermediate' certificate bundled with the issued certificate to trust it.  Here's a bit of a reference I found about the root cause (it's more of a java issue than a godaddy issue)
https://tozny.com/blog/godaddys-ssl-certs-dont-work-in-java-the-right-solution/

I found you can just edit the certificate(.crt file), and paste in the intermediate certificate below the issued one
-----BEGIN CERTIFICATE----- 
issued cert text
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE----- 
intermediate cert text
-----END CERTIFICATE-----

save file...'re-install' the cert and restart server and that solves it...

pretty sure I used the 
gd_bundle-g2.crt 
from godaddy's repository https://certs.godaddy.com/repository
hope that helps

**Comment by joshuawoodward** [comment]
@towhead09 thanks for the info
