### ISSUE TITLE
UNSUPPORTED CONTENT TYPE

### ISSUE THREAD

**Issue by shubh0512** [zoom/api#15]
Hi ! I am facing a problem where in response says 

Unsupported Content Type

 

Below is the log :

Method / Endpoint

POST https://api.zoom.us/v2/users/shubhamnigamknp0512@gmail.com/meetings
 

Headers
accept: */*
authorization: ******
connection: close
content-type: application/x-www-form-urlencoded

Params
 
Body
N/A
 

Response Info : 

Status
415
Headers
Set-Cookie: cred=01412B2127492FF9B9D89729296E73CD; Path=/; Secure; HttpOnly
Data
{
    "code": 300,
    "message": "Unsupported Content Type"
}

**Comment by joshuawoodward** [comment]
Content type needs to be application/json

**Comment by shubh0512** [comment]
Thanks @joshuawoodward
