### ISSUE TITLE
create webinar response

### ISSUE THREAD

**Issue by canbax** [zoom/api#16]
create meeting response is very detailed very useful.
https://zoom.github.io/api/#create-a-meeting

create webinar response is like nothing. I need to make another retrieve call to make it useful. Or does the docs wrong
https://zoom.github.io/api/#create-a-webinar

--edit

I see that create webinar and create meeting respond with the same type.

**Comment by harrisyang** [comment]
@canbax, thanks. It's the docs wrong. We will fix it.
