### ISSUE TITLE
Zoom  - API register for Webinar not sending confirmation email

### ISSUE THREAD

**Issue by VinceMainelistings** [zoom/api#18]
When I register to a webinar using the api, it signs me up to webinar, but does not send the email confirmation.

**Comment by joshuawoodward** [comment]
There are quite a few scenarios for this. I just tested and it works as expected.

It depends on, when webinar is created, what options you pass for approval_type and registration_type. If you don't have auto approval on, you'll have to manually approve registrants through the web ui or api.

An email goes out when a user is approved to attend.

**Comment by VinceMainelistings** [comment]
Great, Thanks!
That was it. I had to turn on the Auto accept for the webinar.
