### ISSUE TITLE
"{\"error\":{\"code\":300,\"message\":\"Api key and secret are required.\"}}"

### ISSUE THREAD

**Issue by endercokcoskun** [zoom/api#2]
I send to api_key and api_secret 
but response messages ="{\"error\":{\"code\":300,\"message\":\"Api key and secret are required.\"}}"

**Comment by joshuawoodward** [comment]
Can you provide more details of what/how you are sending this information?

**Comment by joshuawoodward** [comment]
Closing as no more details provided
