### ISSUE TITLE
Mistake in Docs

### ISSUE THREAD

**Issue by tcash11** [zoom/api#21]
In the v2 API documentation for [Updating a Registrant's Status](https://zoom.github.io/api/#update-a-meeting-registrants-status), the registrant list body argument should be pluralized. If it is singular the request does not work (still returns a 204, but registrant doesn't get updated). Should be:
```
{
	"action": "string", 
	"registrants": [
		{"id": "string", "email": "string"}
	]	
}
```

**Comment by harrisyang** [comment]
@tcash11 Thanks very much, we will fix this error ASAP.
