### ISSUE TITLE
Check a user’s email always returns false

### ISSUE THREAD

**Issue by OsBlaineOra** [zoom/api#25]
When I run a GET on the following endpoint using any email address it always returns false.
`https://api.zoom.us/v2/users/email?email=anyValid.email@example.com`

To double check the email is valid I ran a GET against
`https://api.zoom.us/v2/users/anyValid.email@example.com`
This returns the user object including the email used in both calls.

I have tried this call with multiple valid email addresses.

**Comment by harrisyang** [comment]
@OsBlaineOra , the checked email should be Zoom work email. Can't be google/facebook/sso user.

**Comment by OsBlaineOra** [comment]
My use case is, I'm creating meetings with alternate hosts inside my company (we use SSO).  Not everyone has a Zoom account.  If I attempt to create a meeting with an alt host who doesn't have a Zoom account, the create meeting call fails.

I hoped to use this function to validate the potential alt hosts before attempting to create a meeting.

As a workaround, I currently call `https://api.zoom.us/v2/users/anyValid.email@example.com` and check for a not found error.  From a security standpoint, I'm not comfortable pulling all of the user data down simply to check if it exists or not.  I realize it's a minor security risk and I don't store the data, but there really isn't a reason to move that data in the first place when all I need is a true/false.

Since this API function is part of the user section in the docs and the docs only say "Check if the user email exists", it seems like this should be checking the addresses in the user object returned by
`https://api.zoom.us/v2/users/anyValid.email@example.com`.  Is there a reason this can't be done?
(The same email works in my workaround above)

If this API function is not related to the user object maybe it should be moved out of the user section?

At the very least the docs should be updated to list the limitations of this function.

**Comment by harrisyang** [comment]
@OsBlaineOra, thanks, we will fix the API doc.
Check user email API is used to check if the Zoom work email exist or not.
So if you want to check if the sso user email exist or not, please use user get API. 
https://zoom.github.io/api/#retrieve-a-user
