### ISSUE TITLE
CreateMeeting - settings doesn't include registrants_confirmation_email

### ISSUE THREAD

**Issue by renhammington** [zoom/api#26]
Hi

I'm integrating Zoom management with our intranet, and building a C# wrapper for it. Going through each of the key functions, and have noticed that when creating a meeting, you can't set registrant confirmation emails `settings.registrants_confirmation_email`.  This can only be done by updating the meeting. Seems wasteful to have to create the meeting first, and the update it to affect this setting.

I'm hoping it's just the documentation that's overlooked this,... or is there a reason you can manage this setting when creating a meeting?

**Comment by renhammington** [comment]
... and you can't retrieve this setting as part of the meeting object.

**Comment by harrisyang** [comment]
@renhammington , now we don't support this option in Meeting Create API. 
You can request us a support ticket for this feature.
