### ISSUE TITLE
Change Meeting status

### ISSUE THREAD

**Issue by MartinZbozien** [zoom/api#28]
Hi 
I try end Meeting status using simply action 'end' - sending as PUT - no errors but it do not end meeting could You please check that and confirm that it is working correctly?

Headers seams fine:
HTTP/1.1 204 No Content Date: Tue, 20 Mar 2018 21:04:13 GMT Connection: keep-alive Server: ZOOM Cache-Control: no-cache, no-store, must-revalidate Pragma: no-cache Expires: Thu, 01 Jan 1970 00:00:00 GMT Set-Cookie: cred=D7A92CDA074FED00552224EAA1F32DFE; Path=/; Secure; HttpOnly Strict-Transport-Security: max-age=0

**Comment by harrisyang** [comment]
@MartinZbozien , sorry we can't reproduce this issue, please contact Zoom support and they will be able to help you right away.
