### ISSUE TITLE
Password doesn't work when creating meeting

### ISSUE THREAD

**Issue by honcho26** [zoom/api#3]
I created a meeting via the API and provided a password in my call to meeting/create.  I then verified that the password was saved by calling meeting/list.  When I started the meeting, and then had somebody join, they were not prompted for the password.

**Comment by joshuawoodward** [comment]
@honcho26 please verify again. I just tested this and was prompted for password
![2017-07-31_15-09-11](https://user-images.githubusercontent.com/1133928/28800685-9e58dfd6-7602-11e7-8742-715e479a8d03.png)

**Comment by honcho26** [comment]
Joshua,
I think I figured out the issue.  My application provides the join url that is returned by the meeting API.  That join url embeds an encrypted version of the password as a query parameter, such that the user isn't prompted for it (its the same URL that is shown in the invitation email you can send from the Zoom application).  

In order to make sure the user is prompted for a password, you need to give them the generic join URL, e.g. www.zoom.us/j/{meetingID}.

This would be good to document in the API.

Rich

**Comment by joshuawoodward** [comment]
@honcho26 added that information to docs https://zoom.github.io/api/#create-a-meeting
