### ISSUE TITLE
meeting id is not string

### ISSUE THREAD

**Issue by canbax** [zoom/api#30]
meeting id is not string in version 2. It is 9 digit integer as before. Please correct it. It changes lots of things

**Comment by harrisyang** [comment]
@canbax , thanks very much, can you please help figure out which API?

**Comment by canbax** [comment]
here https://zoom.github.io/api/#create-a-meeting . Please correct the documentation. It has many occurences

**Comment by harrisyang** [comment]
@canbax thanks very much. If you create a recurring meeting with fixed time, so we will response some occurrences.

**Comment by harrisyang** [comment]
@canbax , we will
