### ISSUE TITLE
/v2/users/{user}/recordings doesn't respect From param

### ISSUE THREAD

**Issue by shortstuffsushi** [zoom/api#36]
Hello there,

I've been trying to download and archive a batch of recordings for my employer using this API, but it seems that it doesn't actually take into account the StartDate param, or at least not if it's greater than some duration.

My exact params are `/v2/users/{user}/recordings?from=2017-08-02&to=2018-04-09&page_size=300` -- for my account, this should only end up being ~35 meetings, but instead I'm getting 13. The problem shows up in the response, which indicates it's choosing a start date of 2018-03-09 (a month ago).

So, one of two things is broken -- either the API isn't correctly handling the FROM param or there's some sort of API limitation that should be documented. Can you tell me if I'm missing something here?

Edit: noticed my max page size was beyond the documented max. I adjusted it down to 300, but that didn't fix the date issue.

**Comment by shortstuffsushi** [comment]
After lessening my time frame to a month at a time, I was able to figure out what is likely the problem. This API in particular seems limited to six months of data retention. Probably also worth having documented somewhere.

The website still shows this data, so is there something I could do instead to get this info, aside from screen scraping the site?

**Comment by harrisyang** [comment]
@shortstuffsushi , the query date range is a maximum of one month. For example, if “from” is set to “2017-08-02” and “to” is “2018-04-09” we will adjust “from” to “2018-03-09"

**Comment by harrisyang** [comment]
@shortstuffsushi , thanks very much, we will add this word description.
Now we can only get the recordings in  6 months. You can contact our support to create a ticket, we will consider to enhance this API to support longer report.

**Comment by shortstuffsushi** [comment]
@harrisyang -- couple of questions for you then

 * Why provide a start and end param if you're going to adjust the start to end - one month?
 * Why not just let start be anywhere inside the 6 month range you allow?
 * If nothing else, could this month limitation also be documented?

I've seen mention of contacting support in a couple of other issues as well when I was searching for this, but I didn't see where that is. Should I be looking on the Zoom site for this or something?

**Comment by harrisyang** [comment]
@shortstuffsushi, you can set a start date that starts within 6 months, but the range of start_date and end_date should be in one month. For example, you can set the below values:
1. start: 2018-04-10, end: 2018-04-11
2. start: 2018-03-11, end:2018-04-11
3. start: 2017-12-01, end: 2018-01-01
4. start:2017-12-01, end:2017-12-10

You can also go to our developer site - community to search or ask the questions.
http://developer.zoom.us/
https://support.zoom.us/hc/en-us/community/topics?flash_digest=acb530df3d3342ebdfcd6821d474a46a10331457

**Comment by shortstuffsushi** [comment]
Why would you ever want things to work that way as a consumer of the API? I can specify an arbitrary range (well, as long as it's also in the last six months)... but the range can only be a month or less? That seems totally random.

I was able to (manually) export the data I needed, and will probably not use this API again, but it would be helpful for future consumers if you removed some of these constraints you've added.
