### ISSUE TITLE
CRITICAL: Sorry, the maximum number of user report api requests every day are already reached

### ISSUE THREAD

**Issue by delmicio** [zoom/api#4]
I'm using `/report/getuserreport` to get the quantity of current users in 1 meeting as this is the only endpoint that contains the participants of a meeting.

Please remove the limit or provide a endpoint where we can get participants of a meeting.

Huge problem since this limit was not documented and we're already in production with all of our users saying they can not enter our meetings.

**Comment by joshuawoodward** [comment]
What is the use case where you need to get the participants of a meeting in real time via the rest api? 

This is available in our desktop/mobile SDKs via methods, however the use case is because you can interact with a meeting in real time.

**Comment by delmicio** [comment]
@joshuawoodward  We use this report to send our users in the meeting where the current live participants is lowest and to not allow if the current live participants are greater than X.

**Comment by joshuawoodward** [comment]
Closing this as the end goal is what issue #1 is asking for.

**Comment by delmicio** [comment]
@joshuawoodward this problem is related but is not the same. 
This issue is about the limit imposed when getting the report. This limit is not documented and we build our meetings upon this feature. 

Could you please provide more information about this limit? who much is it?

**Comment by joshuawoodward** [comment]
@delmicio from what I can gather from internal documentation this endpoint is rate limited to 1 call per day. The API is designed for reporting (run a cron job once per day), not realtime data gathering. I understand your use case and am investigating an alternative solution.

Agree we need to expose this information (rate limits) externally and will work on that aspect.

**Comment by joshuawoodward** [comment]
Documentation added https://zoom.github.io/api/#rate-limits
