### ISSUE TITLE
Host can't start meeting  which is scheduled for tomorrow or later

### ISSUE THREAD

**Issue by canbax** [zoom/api#44]
As a free user or as a pro user I created a meeting for tomorrow. When I go to meeting start url. It is fine.

After one day when I go to the start url, it redirects me to the sign in page. Here is an example link

[https://vedubox.zoom.us/s/749470598?zak=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjbGllbnQiLCJ1aWQiOiJPVXQ4TlJjQVFiR1d6M3pKZmFEV013IiwiaXNzIjoid2ViIiwic3R5Ijo5OSwiY2x0IjowLCJzdGsiOiJQU1c4OUpRQjVPUGlhV3hZQXdpY1ZxczB1STM3X3UwQU1pQWd1bnlwQWpzLkJnUkFiMHBhVlRkVlRVSlBia3BrZEhWYVdEQndNbmhwZFVkbWNGUkVVVnBITW1sTWFtZHFjVmR0ZGxOdGJtTnZjRm96UnpsR09XMXRWazUxTldwQk4yWnFOZ0FBRERORFFrRjFiMmxaVXpOelBRQSIsImV4cCI6MTUyNjYzOTI5NSwiaWF0IjoxNTI2NjMyMDk1LCJhaWQiOiJ1T3dxWkd2aFJRNjVpM0J0RFFha1pBIiwiY2lkIjoiIn0.xyz1R-S2_aoAcslbROdhWBXs_XY4RTuMnGLcFZ8rV-Y](url)

I think the reason is expiration of users **zak** token. Where could we set the expire date for user? I couldn't find in API documentation. There is only one **zak** word in the whole documentation

**Comment by canbax** [comment]
I found how could I fix the problem. The start URL of a meeting is changing overtime. Start url must be updated

**Comment by harrisyang** [comment]
@canbax , oh sorry, the expire time of zak is 2 hours. We will update the API doc ASAP. Thanks.

**Comment by harrisyang** [comment]
@canbax , sorry, we can extend the expiration time only for API users.

**Comment by canbax** [comment]
Thank you @harrisyang Good to know
