### ISSUE TITLE
I create a zoom meeting, but I can't open meeting with start_url.  

### ISSUE THREAD

**Issue by anime8992** [zoom/api#45]
the start_url is here: 
https://zoom.us/s/246728634?zak=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjbGllbnQiLCJ1aWQiOiI1V0JHNGJCUlJIdUxlN0p4U2lhZHdnIiwiaXNzIjoid2ViIiwic3R5Ijo5OSwiY2x0IjowLCJzdGsiOiJSTzB0ei1HbVRMLXVqOWg0dXd4Y1hnelNDcFZfam9lZHR0SEtYVFo1RnVJLkJnUXNja2t2VjJwNU1WZG1jM0JrYWxsd1RsQlpjRE13ZW1Oa1lVWlNhbGg1ZFZKcVpuZHpNVlpRU21WRFNUMEFBQXd6UTBKQmRXOXBXVk16Y3owQSIsImV4cCI6MTUyNjk3NDU5NywiaWF0IjoxNTI2OTY3Mzk3LCJhaWQiOiJlbHFtZVhyUlRYYTJITGhjc09EWHZBIiwiY2lkIjoiIn0.eLVRji9V2zu33-1vW0u_Icks2tfq0v5QD7TsQN1mlTo
![Uploading 微信截图_20180522163817.png…]()

**Comment by harrisyang** [comment]
@anime8992 , this start_url is expired, please get a new start url via MeetingGet API.
