### ISSUE TITLE
integration problem 

### ISSUE THREAD

**Issue by ayaolwan** [zoom/api#49]
hi there, I am looking for zoom documentations https://zoom.github.io/api/ but  I don't know what I need to call at my web site , so zoom work well to me , I call api link as  https://api.zoom.us/v2/users/  evert time give me false  can any one help me

**Comment by michaelZoomDA** [comment]
Hi @ayaolwan, please look at the Quick Start guide located https://developer.zoom.us/docs/api/. Also, be sure to use JWT in our header when calling APIs.
