### ISSUE TITLE
Recording file duration is not correct

### ISSUE THREAD

**Issue by voxxit** [zoom/api#5]
We are running into an issue whereby we take the `recording_start` and `recording_end` from a `/v1/recording/get` request, and subtract that to get a duration. It seems as though you are using this to calculate the duration in your video player, as well.

Unfortunately, that is not calculating the right duration. Example:

```json
{
      "id": "8e622bb9-6161-4433-9e10-...",
      "meeting_id": "...",
      "recording_start": "2017-07-27T22:16:36Z",
      "recording_end": "2017-07-27T22:22:43Z",
      "file_type": "MP4",
      "file_size": 15466797,
      "play_url": "https://api.zoom.us/recording/play/...",
      "download_url": "https://api.zoom.us/recording/download/..."
    }
```

[7] pry(main)> ts_end = Time.parse("2017-07-27T22:22:43Z")
=> 2017-07-27 22:22:43 UTC
[8] pry(main)> ts_start = Time.parse("2017-07-27T22:16:36Z")
=> 2017-07-27 22:16:36 UTC
[9] pry(main)> ts_end - ts_start
=> 367.0

However, this video (when we download and play in VLC/QuickTime) is *actually 246 seconds long*. See attached:

<img width="350" alt="screenshot 2017-07-27 15 54 57" src="https://user-images.githubusercontent.com/12201/28695423-f5eb97ec-72e3-11e7-90c0-7c82b055c985.png">

**Comment by joshuawoodward** [comment]
This is not an issue with the REST API, but an issue with the zoom video player UI. Closing here but will follow up with that team.

**Comment by nevinera** [comment]
The timestamps given by the API are incorrect for the video file in question - how can that be a UI issue?

**Comment by voxxit** [comment]
It's not? Is there a reason why the _REST API_ returns invalid time, not to mention the far-from-valid `duration` value?

**Comment by joshuawoodward** [comment]
Misunderstood the issue..
Reopened and investigating

**Comment by joshuawoodward** [comment]
This should be fixed in Zoom Web Release on 8/26/17
