### ISSUE TITLE
opening the start url, it redirects me to the sign in page

### ISSUE THREAD

**Issue by tuotempo** [zoom/api#51]
We use API v1 to create cust users and then create for them scheduled meetings. For a month or so our customers complain that the start url, that we send them via email / sms, no longer works. They say they are redirected to the sign in page.
I read that the session token (zak) expires after 2 hours.
I would like to know two hours since when? From the first opening of the link?
I also wonder if it could be a problem that we shorten the start url via the TinyURL or Google URL Shortener service?

**Comment by harrisyang** [comment]
@tuotempo , now the expiration time of start_url is 2 hours, but for API users, the expiry time is 90 days.

**Comment by tuotempo** [comment]
OK, but we use the "Meeting" API (https://api.zoom.us/v1/meeting/create) to create scheduled 
meetings for them, so the zak token expires in 2 hours, right? 2 hours from the first opening of the link (start url)?

**Comment by harrisyang** [comment]
@tuotempo , if the meeting host is not an API user, so the expiration time is 2 hours. That means the host can launch this meeting with this start_url in 2 hours.

**Comment by tuotempo** [comment]
OK. Thank you @harrisyang
