### ISSUE TITLE
Missing list all live meetings endpoint

### ISSUE THREAD

**Issue by delmicio** [zoom/api#58]
Hi, I'm updating our code to use v2 instead of v1 and the list all live meetings endpoint is not longer there.
https://zoom.github.io/api-v1/#list-live-meetings

I do see a list host live meetings with a filter by live but that is much much slower as I need to retrieve all active hosts and then retrieve for each one all live meetings.

Please add the endpoint to retrieve all live meetings without the host id parameter or make the host id optional if live parameter is present.
https://zoom.github.io/api/#list-meetings

**Comment by michaelZoomDA** [comment]
Hi @delmicio our Engineering team will take note of this see if we can add this feature for a future release.
