### ISSUE TITLE
Upload User Picture documentation innaccurate

### ISSUE THREAD

**Issue by nickrod518** [zoom/api#6]
The documentation for the Upload User Picture endpoint is not accurate. The example simply has a URL to a jpg as the pic_file parameter, but this parameter needs to be a byte array of a jpg. Further, the request must be submitted as a multipart request. This particular endpoint caused me a lot of headache originally and so it would be nice if it was accurate to avoid the same issue for others.

P.S. I'm happy to see the Zoom's REST API has moved to GitHub where issues can easily be submitted.

**Comment by joshuawoodward** [comment]
Will get this fixed ASAP

**Comment by joshuawoodward** [comment]
The docs have been update https://zoom.github.io/api/#upload-user-picture
