### ISSUE TITLE
Webhook for Webinar End

### ISSUE THREAD

**Issue by lakshsyal123** [zoom/api#60]
Hello, Do we have any webhook when the webinar is ended? 
I am working on a software where I need that notification... Can anyone help me to know about this? 

Thanks

**Comment by michaelZoomDA** [comment]
Hi @lakshsyal123 Yes we have a webhook for when a webinar has ended. Please refer to our marketplace webhooks. https://devdocs.zoom.us/docs/marketplace-reference#section-payloads-for-meeting

**Comment by lakshsyal123** [comment]
Hello Michael,
Can you clarify me "auth_user", "auth_password" What needs to come in this.

Thanks

**Comment by lakshsyal123** [comment]
I wanted to know one Last Thing, 
I can only setup one Webhook in one account, so if my user already having a Webhook to xym.com than I can either update it, and that might cause him to loose data to "xyz.com" the one he already have.
Can you suggest something for this?

**Comment by michaelZoomDA** [comment]
Hi @lakshsyal123 Can you elaborate on this a little bit more? Do you want to collect the saved data from xym.com for the user before updating it?

**Comment by lakshsyal123** [comment]
Hey @michaelZoomDA My scenario is for example a person is using zapier and their he integrated a  webhook for some purpose. 
Now he wanted to use my software also. Where I would also be creating a webhook my project.
At that time I would get stuck to create a new webhook because the API will throw the error that "only one webhook can be create at one account" and at that time either I can update that previous webhook  but if I did that it will impact his Zapier Project.

Let me know if my question is clear to you now.

Thanks

**Comment by michaelZoomDA** [comment]
Hi @lakshsyal123 Thanks for the clarification. To help with your situation, you could use our [marketplace](https://marketplace.zoom.us/) and create an separate app for the person using Zapier and they could use [event subscription](https://devdocs.zoom.us/docs/subscribing-to-zoom-events-1).

**Comment by michaelZoomDA** [comment]
Closing this issue.
