### ISSUE TITLE
Is there a /whoami type endpoint?

### ISSUE THREAD

**Issue by nigelellis** [zoom/api#64]
Hi, 

I'm building an integration with Zoom and have successfully authenticated via. OAuth2.   I'd like to resolve the current auth-token I have to a zoom user so I can get the display name, email address, etc.   How do I do that in the API?  AFAICT the user APIs all require me to pass in a userId.

Thanks,
Nigel.

**Comment by nigelellis** [comment]
For anyone looking, this API is available at `/v2/users/me`.   Sadly these documents are not up to data and there are additional API endpoints available via. OAuth. at https://developer.zoom.us/docs/oauth/

**Comment by michaelZoomDA** [comment]
Hi @nigelellis, we're glad that you were able to find the /me endpoints. We are currently in the process of migrating all of our documentation to https://devdocs.zoom.us/docs/permissions for a better developer experience. Please let us know if you have any other questions.

**Comment by nigelellis** [comment]
Thanks, that's super helpful.

Can you outline the process / configuration that I use to set the scopes required by my integration?   If I specific scopes in the oauth flow I currently get an error.

For my app, I need: meeting:read, user:read, webinar:read.   

Thanks,

Nigel.

...

**Comment by michaelZoomDA** [comment]
Hi @nigelellis, I assuming you used OAuth using developer.zoom.us, correct? If so, we don't have an option to set your scopes using that site anymore.  To set specific scopes such as meeting:read, user:read, webinar:read, you will need to use our new marketplace, it's the same OAuth flow but you will need to create an app there. To get started go here - https://devdocs.zoom.us/docs/introduction. 

Let us know if you need anything else.

**Comment by nigelellis** [comment]
Thanks, looks like you're moved everything to the marketplace model.   What's the main website that I used to configure this?   I couldn't find a link in the docs.

Thanks.

...

**Comment by michaelZoomDA** [comment]
Hi @nigelellis, the website is https://marketplace.zoom.us/ from there you can use https://devdocs.zoom.us/docs/building-integrations.
