### ISSUE TITLE
API docs are missing OAuth endpoints

### ISSUE THREAD

**Issue by nigelellis** [zoom/api#65]
These docs are missing valuable OAuth APIs endpoints documented in https://developer.zoom.us/docs/oauth/

Please fix!   I wasted a bunch of time trying to hunt things down.

**Comment by michaelZoomDA** [comment]
Hi @nigelellis, please see for OAuth APIs https://devdocs.zoom.us/docs/permissions.

**Comment by nigelellis** [comment]
Thanks Michael, that's exactly what I was looking for.   It would appear Zoom is moving away from the current REST API model and integrating this with the new Zoom Marketplace Apps eco-system.  Would be great if you can update the docs here to reflect that, or make a statement clarifying the relationship.

**Comment by michaelZoomDA** [comment]
Hi @nigelellis,  thanks for the feedback, we're making the updates to our documentation as we speak to improve the developer experience.
