### ISSUE TITLE
No Cloud Recording API

### ISSUE THREAD

**Issue by Nicosoft** [zoom/api#8]
Hi there,

In version 2, I cannot see any methods regarding Cloud Recording API, like in version 1 https://api.zoom.us/v1/recording/*..

How am I supposed to manage recording files for a meeting through the API?

Thanks.

**Comment by joshuawoodward** [comment]
@Nicosoft we are working to add the recording APIs to version 2 #staytuned

**Comment by Nicosoft** [comment]
Awesome! Looking forward to playing with it.

**Comment by ianwinsemius1** [comment]
Please update with an ETA, and a roadmap for the new API if its available. This is a critical system, and I would like to know if I'm going to have to plan contingencies prior to 11/1/18 when v1 sunsets.

**Comment by joshuawoodward** [comment]
@ianwinsemius1 next release (Dec '17 timeframe)

**Comment by ianwinsemius1** [comment]
Awesome! Thanks, looking forward to checking it out!
