### ISSUE TITLE
Allow to disable "Record an audio only file" on user settings

### ISSUE THREAD

**Issue by delmicio** [zoom/api#8]
![image](https://user-images.githubusercontent.com/2908209/29035391-cbf6f0da-7b71-11e7-85c8-67b11d2ad7fc.png)

This option is missing with the API. We need this to save space in our account.

**Comment by joshuawoodward** [comment]
Will take a look

**Comment by joshuawoodward** [comment]
https://zoom.github.io/api/#update-user-info

enable_record_audio_file
