### ISSUE TITLE
Tracking field APIs has extra version path

### ISSUE THREAD

**Issue by nguyenhthai** [zoom/api#87]
Based on the latest openapi specs for the new API update, I noticed that the new tracking field Api does contains extra "v2" in the path. It should be "/tracking_fields" instead of "/v2/tracking_fields".

**Comment by michaelZoomDA** [comment]
Hi @nguyenhthai thanks for pointing that out, we'll make the correction shortly.

**Comment by michaelZoomDA** [comment]
Closing
