### ISSUE TITLE
View ALL cloud recordings for an account?

### ISSUE THREAD

**Issue by qckpckt** [zoom/api#9]
I'm trying to automate the process of moving cloud video recordings to google drive, and I can see that the current cloud recordings API lets me search for recordings for an individual user ID. 

Is there a global account ID that I can use to see _all_ recordings? 

It's pretty hard to know what cloud recordings there are if you also need to know who the host was each time.

**Comment by joshuawoodward** [comment]
There is not a global list recordings API, it is per user. However there is a option via webhooks to be notified when a recording is complete https://zoom.github.io/api/#webhooks
